import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Chess</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="mx-auto w-[90vmin] h-[90vmin] bg-zinc-900">ok</div>
    </>
  );
};

export default Home;
